#!/bin/sh

check_all_files() {
  if ! which git-clang-format &> /dev/null; then
    echo -e "\n\n git-clang-format was not found in your PATH"
    exit 1
  fi
  if ! git-clang-format --diff --staged; then
    echo "Commit aborted due to formatting errors. You can:"
    echo "- Fix the errors, e.g. with git-clang-format"
    echo "- Disable checks on section of the code with:"
    echo "   // clang-format off"
    echo "   code"
    echo "   // clang-format on"
    echo "- Ignore the issue by using git commit --no-verify (not recommanded)"
    exit 1
  fi
}

case "${1}" in
 --about )
   ;;
 * )
   check_all_files
   ;;
esac
# Clang Format Hook - End
