#!/bin/sh

check_all_files() {
  if ! which clang-format &> /dev/null; then
    echo -e "\n\n clang-format was not found in your PATH"
    exit 1
  fi
  format_valid=true
  for file in $(git diff-index --cached --name-only HEAD | grep -iE '\.(cc|h)') ; do
    if [[ -f "$file" ]]; then
      diff=$(clang-format -style=file ${file} | diff -u "$file" -)
      if [ $? -ne 0 ]; then
        echo "Invalid clang-format for $file:"
        echo
        echo "$diff"
        echo
        format_valid=false
      fi
    fi
  done

  if [ $format_valid = false ]; then
    echo "Commit aborted due to formatting errors. You can:"
    echo "- Fix the errors, e.g. with make clang-format"
    echo "- Disable checks on section of the code with:"
    echo "   // clang-format off"
    echo "   code"
    echo "   // clang-format on"
    echo "- Ignore the issue by using git commit --no-verify (not recommanded)"
    exit 1
  fi
}

case "${1}" in
 --about )
   ;;
 * )
   check_all_files
   ;;
esac
# Clang Format Hook - End
